### ISSUE TITLE
Question: How can errors in tap output be represented in tap-out?

### ISSUE THREAD

**Issue by matthewdunsdon** [scottcorgan/tap-out#26]
There are several cases when all the tests pass, however the overall tap input indicates a problem.

Could the output of tap-out include an errors section in the response and / or introduce an 'error' event? 

### Context

The main case I am seeing is when test file dies silently in the middle of its run.  When this happens you get the following output from tap.

```
ok 1
ok 2
ok 3
ok 4
```

This output should be treated as an error because the test died before plan section is written (i.e. `1..5`). The output from tap-out@1.4.2 is included on [one of my gists](https://gist.github.com/matthewdunsdon/6ceb452c9edb880e53ceabd21f55a50f).

To work around this in the short term, I could verify that the `plans` property from tap-out is not an empty array — _technically `plans` property is not documented in README.md_.

Because there are more error cases that can occur, such as having more tests run than are initially planned, it could be beneficial for consumers to opt into reading this new data or listening to an additional event rather than detecting these errors themselves.

**Comment by scottcorgan** [comment]
Good find. I'm open to a PR.

Also, could you test, the module that was meant to replace this one is https://github.com/tap-format/parser.

**Comment by matthewdunsdon** [comment]
We have a PR created for tap-out, which should hopefully be a place for discussion what the preferred mechanism is for outputting errors.

**Next action:** take a look into <https://github.com/tap-format/parser>.

-----------

_Question: Is the intention that the tap-out will be be deprecated and that @tap-format/parser is the recommended library to use instead?_

If tap-out is not being maintained anymore and you are just using a different library yourself, then a [deprecation notice](https://github.com/substack/node-optimist/commit/815c965cee7682ae2c6a80f8b306d20c81eb199a) on the README file and doing an [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) could be helpful to the community.

**Comment by scottcorgan** [comment]
Thanks for the PR! I'll review the PR in a bit.

As far as deprecating this package, I don't think I'm going to deprecate it. It seems to be popular and has held up well over the years.

**Comment by scottcorgan** [comment]
Closed by https://github.com/scottcorgan/tap-out/pull/27

**Comment by matthewdunsdon** [comment]
Have taken a look at <https://github.com/tap-format/parser>, and there are similar issues there as well.  

Because it is event / observer based, I am not sure if a different approach is needed.  I think it might be worth doing, as it allow consumers to listen to errors rather than having to verify that no plan events has been emitted.
